"""Adding session table for adding sessions for the user

Revision ID: 58827328e9a1
Revises: 
Create Date: 2026-03-12 20:53:40.518891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58827328e9a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('notes', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_session')
    # ### end Alembic commands ###
